name: Deploy

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Deploy
      env:
        INFURA_URL: ${{ secrets.INFURA_URL }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        npx hardhat run scripts/deploy.js --network sepolia
